language: java

addons:
  apt:
    packages:
    - graphviz
    - xmlstarlet

jdk:
- oraclejdk11

install: skip

script:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- if ./can_auto_deploy.sh  ; then mvn deploy -B -U --settings settings.xml; else mvn verify -B -U; fi

env:
  global:
  - secure: WW9RYDx++aTX32ChLATrhJiKJ///WFk0GZnu3wQrNWQgLxIBkWavZRJii6ZOdKdTMUo6lU6pIos0tX1BAgrRSAFRVbrwLh9PD+wbrlAlkhSVnVylW4RxWLKJyFLG4Xtb1EITneZlVS7lBdGrt9344pm3VEyOcXdW6wkG+bpcgQUOu2/v6GBg4rjXh6p5gLVxbwy27sTzxfzpxvCR3EesyFbiX1D6LzCYxb2kP0JJeKUAblI4skKEwxGnb8NEtKDXsVoqVSUIaq304H9U4KUHBDB3TaPEyGejnf8B0Ub0nIawN5zkw8nMh/68t4gPnoTLIKuWRKRVt8Y4LCwO6fRXI2kmIWvSrqIDgnFvhE0uKcpACdtVYYDXvcudESetUuqWGUeBGU2/9cRU8+kW/PDEGOfX0+aLKXjtjrT95o+vjMv0tKCyptIM1nlvFuzhPyLJmGvOFlf4hdr5P8T+IypJoKcFtic3G1wGWv/WIvgNqoEEZBiDB73FK1+ADDaMyXSx2SRTN3Lhj5HWli5bFeVxzg8WiGRjqaUUnRRdUPCTF5sbZHT0q8Gd0Hr5VCDcOuARNDKbTeT/7DLAW5XcemW0Uxz3FWk7ItPqRwkEigAgU9nbkoWfSZcr+tJZj3lhJmWRWv0uQ4cQFWImnWm4HvdFlOPlUoBe8cvs22IyLyMiq9o=
  - secure: Bk7X39/JfdxAIsq+azY9VjCMiH+LzV8rdELqeyNYkB+QraJTAsoPn3G39Dn37L4bkkXEx9JGDWthUzl5RBUI9JAau6N7/nJSGMgXPTADlIzOlSnM65/mD7WHu2QXdCNe6DzqptWKWSWkjVjsSvS6hdj1knlWt4Zl+PVKChYn3A4kkXWX69N5+1oyuqwuoWqUiQkJk8GX4+hhqEmwm52K1FRt6gwHNtnGVaNCrpYDrxmm/iwYBoTedUppOf9/lpZoFaONoofok83XFlcsUqw9DG+caze//pahuXwPqWQ1nz8gr/fqZ+n4OKVL+1bVoF/txqzbKNAlBAnHRc9j46fHIqM77gXqRhx1P+qVE7oVuIMyuESwDXkfYRTWzyKTho8yv6W5VJtHDPDrfIXKIIQXjnaYRC2xrQz31xj/JyVG1Q1L1odn8/nRps87pvPE7twZ45tMfS1zaEubSM8grAFm2o5infZYYawAyaQ63oswLLxznlV4g3xsryzt8Eybo+srJMVNKTqy3jrDZVFNevEYhiy6/P3MeUpdZTnx+XnXgRh5j3/bWnfC8uTEexmt+Q2YT7+D/9AZKOH45YPpMNwHxTw1TcHJoJTCcwvJ2aRs8zJKT4ziGz+g6EZbpLYYIJr6afrR0an1s2dtoGslrL+jat99apgPVMZH3YYbf4SSf8Q=
